# Each route describes how an incoming URL will be processed by Platform.sh.

"http://{defualt}/":
    type: upstream
    upstream: "ll_project:http"

"http://www.{default}/":
    type: redirect
    to: "http://{default}/"